# Generated by Django 4.2.1 on 2023-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_portfolio_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='is_UIUX',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_game',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_graphic_design',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='is_webdev',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
