# Generated by Django 4.2.1 on 2023-08-12 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_portfolio_is_uiux_portfolio_is_game_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='urltproject',
            field=models.URLField(blank=True, null=True),
        ),
    ]
